# For ndarray arithmetic operations happens element wise

In [1]:
import numpy as np

In [2]:
x = np.array([[6,7],[8,9]]) # Arrays must have the same shape. If they do not, numpy will apply the broadcasting three rules.
y = np.array([[5,6],[7,8]]) # Arrays must have the same shape. If they do not, numpy will apply the broadcasting three rules.

print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x//y) # Integer division
print(x % y) # Modulus
print(x**y) # Power

[[11 13]
 [15 17]]
[[1 1]
 [1 1]]
[[30 42]
 [56 72]]
[[1.2        1.16666667]
 [1.14285714 1.125     ]]
[[1 1]
 [1 1]]
[[1 1]
 [1 1]]
[[    7776   117649]
 [ 2097152 43046721]]
