# Introduction:
NumPy (Numerical Python) is a powerful open-source Python library used for numerical computing, providing support for large, multi-dimensional arrays and matrices along with a wide range of high-performance mathematical functions to operate on them. It is the foundation of many scientific and data analysis libraries in Python, enabling fast operations such as linear algebra, Fourier transforms, and statistical calculations. Unlike regular Python lists, NumPy arrays are more memory-efficient and allow vectorized operations, meaning calculations can be applied to entire arrays without explicit loops, making programs faster and cleaner.

### Creating N-dimensional array using zeros() function

In [1]:
import numpy as np

m = 4
n = 6
o = 7

In [2]:
a=np.zeros(m) # 1 dimensional array (1D)
a

array([0., 0., 0., 0.])

In [8]:
b = np.zeros((m, n)) # 2 dimensional array (2D)
# So, we can create N-dimensional array of arbitrary rank
c = np.zeros((m, n, o)) # 3 dimensional array (3D)
print(f"2D array:\n{b}\n\n3D array:\n{c}")

2D array:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

3D array:
[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]


### Array info.

In [12]:
print(f"Row X Column of a: {a.shape}")
print(f"Rank of a: {a.ndim}")
print(f"Size of a: {a.size}\n")

print(f"Row X Column of b: {b.shape}")
print(f"Rank of b: {b.ndim}")
print(f"Size of b: {b.size}\n")

print(f"Matrix X Row X Column of c: {c.shape}")
print(f"Rank of c: {c.ndim}")
print(f"Size of c: {c.size}\n")

Row X Column of a: (4,)
Rank of a: 1
Size of a: 4

Row X Column of b: (4, 6)
Rank of b: 2
Size of b: 24

Matrix X Row X Column of c: (4, 6, 7)
Rank of c: 3
Size of c: 168

