# Linear Algebra

In [1]:
import numpy as np
import numpy.linalg as linalg

### Matrix Transpose

In [2]:
x = np.arange(40).reshape(20,2)
print(x)
x.shape

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]]


(20, 2)

In [7]:
x = x.T # Matrix transpose (row becomes column and column becomes row)
print(x)
x.shape

[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]]


(2, 20)

### Dot product

In [15]:
a = np.array([[4,7,8,9],[78,-48,4,1]])
b = np.array([[1, 7], [7, 4], [3, 6], [2, -7],])
print(b.shape)
a.shape

(4, 2)


(2, 4)

In [16]:
dotProduct = a.dot(b)
dotProduct

array([[  95,   41],
       [-244,  371]])

### Determination of a matrix using numpy.linalg module

In [17]:
linalg.det(dotProduct)

np.float64(45249.00000000003)

### Diagonal and trace

In [18]:
np.diag(dotProduct)

array([ 95, 371])

In [21]:
print(np.diag(dotProduct).sum())
np.trace(dotProduct)

466


np.int64(466)

# Solving system of linear scalar equations

In [30]:
m1 = np.array([[2, 6], [5, 3]])
m2 = np.array([6, -9])

result = linalg.solve(m1, m2)

print("x = ", result[0])
print("y = ", result[1])

x =  -3.0
y =  2.0


In [31]:
print(m1.dot(result), m2) # Result will be correct if these two are same.
np.allclose(m1.dot(result), m2) # True means result is correct.

[ 6. -9.] [ 6 -9]


True

### Vactorization

In [32]:
xAxis = np.arange(1024)
yAxis = np.arange(768)

x, y = np.meshgrid(xAxis, yAxis) # Generates two matrices from coordinate vectors
x, y

(array([[   0,    1,    2, ..., 1021, 1022, 1023],
        [   0,    1,    2, ..., 1021, 1022, 1023],
        [   0,    1,    2, ..., 1021, 1022, 1023],
        ...,
        [   0,    1,    2, ..., 1021, 1022, 1023],
        [   0,    1,    2, ..., 1021, 1022, 1023],
        [   0,    1,    2, ..., 1021, 1022, 1023]]),
 array([[  0,   0,   0, ...,   0,   0,   0],
        [  1,   1,   1, ...,   1,   1,   1],
        [  2,   2,   2, ...,   2,   2,   2],
        ...,
        [765, 765, 765, ..., 765, 765, 765],
        [766, 766, 766, ..., 766, 766, 766],
        [767, 767, 767, ..., 767, 767, 767]]))

In [36]:
s = np.sin(x*y / 40.5) # The efficient way to do calculation on a matrix.
s

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.02468885, 0.04936265, ..., 0.07705885, 0.1016508 ,
        0.12618078],
       [0.        , 0.04936265, 0.09860494, ..., 0.15365943, 0.20224852,
        0.25034449],
       ...,
       [0.        , 0.03932283, 0.07858482, ..., 0.6301488 , 0.59912825,
        0.56718092],
       [0.        , 0.06398059, 0.12769901, ..., 0.56844086, 0.51463783,
        0.45872596],
       [0.        , 0.08859936, 0.17650185, ..., 0.50335246, 0.42481591,
        0.34293805]])

# Saving and loading

In [39]:
np.savetxt("my_array.csv", s) # saving
k = np.loadtxt("my_array.csv") # loading
k

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.02468885, 0.04936265, ..., 0.07705885, 0.1016508 ,
        0.12618078],
       [0.        , 0.04936265, 0.09860494, ..., 0.15365943, 0.20224852,
        0.25034449],
       ...,
       [0.        , 0.03932283, 0.07858482, ..., 0.6301488 , 0.59912825,
        0.56718092],
       [0.        , 0.06398059, 0.12769901, ..., 0.56844086, 0.51463783,
        0.45872596],
       [0.        , 0.08859936, 0.17650185, ..., 0.50335246, 0.42481591,
        0.34293805]])

In [40]:
np.save("my_array", s) # Default saving
p = np.load("my_array.npy") # loading
p

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.02468885, 0.04936265, ..., 0.07705885, 0.1016508 ,
        0.12618078],
       [0.        , 0.04936265, 0.09860494, ..., 0.15365943, 0.20224852,
        0.25034449],
       ...,
       [0.        , 0.03932283, 0.07858482, ..., 0.6301488 , 0.59912825,
        0.56718092],
       [0.        , 0.06398059, 0.12769901, ..., 0.56844086, 0.51463783,
        0.45872596],
       [0.        , 0.08859936, 0.17650185, ..., 0.50335246, 0.42481591,
        0.34293805]])